### PR TITLE
Upgrade to Alfred 3 and OAuth

### PR DESCRIPTION
**Pull request by jorgesanzx**
Credits to @therealscottcarlow for helping in the issues #1 and #2.

### CODE REVIEW

**Comment by therealscottcarlow** [comment]
Thanks for taking the time to do this @jorgesanzx. I kinda swooped in, said some stuff, then completely forgot to make a PR as I swooped back out. You're the real MVP. 🥇

**Comment by mannieschumpert** [comment]
Thanks for the help @jorgesanzx and @therealscottcarlow ! 
To be honest, I only did a quick review of the changes, but it all looks kosher. Sorry for the delayed response.

**Comment by SuryaSpa** [comment]
Coding, even in this simplest form, is not my world, though I'm good in my worlds!  I could use help, and would even be happy to remunerate, for a little help with the akey issue -- I first tried API, then created token, but am failing (on a new computer) to find and deal with replacements to "increase workflow version" from 2-3.   My email is roger@suryaspa.com -- and I would hugely appreciate help as Alfred Quick Task to asana is a wonderful part of everything!  Thank you-- Roger

**Comment by therealscottcarlow** [comment]
@rogersoffer If you're having problems you will get much better visibility if you opened an issue describing the problem and going into detail on what you have attempted so far to fix it. This is a closed PR, nobody's going to see this aside from people who have already commented on it.

Also, I would refrain from putting your email into a very public forum like this unless you like spam. :)

**Comment by ialexryan** [comment]
@mannieschumpert thank you for merging this – I know you're busy, but do you think we could get a new release made for v2.2? The link on http://mannieschumpert.com/quicktask/ still points to v2.1 and I'm sure plenty of people are finding it and being sad that it doesn't work with Alfred 3 😞

**Comment by jjarava** [comment]
Just as a FYI @ialexryan, if needed to upgrade/install, you can just get the master source, uncompress it, and copy the folder to your "workflows" directory in Alfred

See the details in this thread on the Alfred forums about _this_ workflow:

[Asana Quick Task](https://www.alfredforum.com/topic/2801-asana-quick-task/?do=findComment&comment=63846)
<https://www.alfredforum.com/topic/2801-asana-quick-task/?do=findComment&comment=63846>


Not pretty, but a way to get it working!

**Pull request merged**
